name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.rdoc'
      - 'src/**/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/create-github-app-token@v3
        id: koans-deploy-app-token
        with:
          app-id: ${{ vars.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_SECRET_KEY }}
          owner: werebus
          repositories: ruby_koans
          permission-contents: write
      - uses: actions/checkout@v7
        with:
          token: ${{ steps.koans-deploy-app-token.outputs.token }}
      - run: 'rake package'
      - run: |-
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add download/
          git commit -m 'Update download .zip file [skip ci]' || true
          git push
